### PR TITLE
final product. fixed all html and css conflicts.

### PR DESCRIPTION
**Pull request by aww2539**

### CODE REVIEW

**Review by DArmstrong87 — APPROVED** [review]
Everything is god-awful in appearance and working correctly. Ready for final merge!

**Review by zbrhoden — APPROVED** [review]
completely terrible!

**Comment by shanks-t** [comment]
looks dope!

**Review by shanks-t — APPROVED** [review]
looks good

**Review by JCrippen01 — APPROVED** [review]
Wow this is awesome. Can I pay you double?

**Pull request merged**
