### PR TITLE
moved slideshow section code into the main article. edited slideshow.…

### PR DESCRIPTION
**Pull request by aww2539**
…css to match article.worst_mug_ad dimensions. edited coffeeAd.css so that elements fit a little better along with adding a hover action to mug_img.

### CODE REVIEW

**Comment by aww2539** [comment]
Enjoy. Let me know if anything needs changed or if you have suggestions for improvement.

**Comment by JCrippen01** [comment]
Looks good to me. Tested in chrome and mozz

**Review by JCrippen01 — APPROVED** [review]
Looks good, or terrible. Tested with Mozz and chrome.

**Review by zbrhoden — APPROVED** [review]
looking awful

**Pull request merged**
